contrib/accounts/urls.py
from django.urls import path
from django.conf.urls import include, url

from .views import SignInView, SignOutView, UserProfileViews, user_profile, sign_up, signout_user, SignUpViews
from django.contrib.auth.views import LoginView, LogoutView 

app_name = 'accounts'


urlpatterns = [
    # path('singin/', LoginView.as_view(), name="login"),
    path('singin/', SignInView.as_view(), name="login"),
    # path('signout/', signout_user, name="signout_user"),
    path('signout/', SignOutView.as_view(), name="signout_user"),
    # path('profile/', user_profile, name='current_user_profile'),
    path('profile/', UserProfileViews.as_view(), name='current_user_profile'),
    # path('profile/<int:id>/', user_profile, name='user_profile'),
    path('profile/<int:id>/', UserProfileViews.as_view(), name='user_profile'),
    # path('signupacc/', sign_up, name='sign_up'),
    path('signupacc/', SignUpViews.as_view(), name='sign_up'),

]

from .receviers import *

contrib/petstagram/urls.py
from django.urls import path
from .views import SearchResultsView


from .views import CreatePetViews, EditPetViews, LandingPageViews, PetCommentViews,\
                PetDedailsView, PetDeleteViews, PetLikeViews, PetsListViews, \
                landing_page, pet_list, pet_detail, pet_like, pet_edit, pet_delete, pet_create

app_name = 'petstagram'


urlpatterns = [
    path('search/', SearchResultsView.as_view(), name='search_results'),
    # path('', landing_page, name='landing_page'),
    path('', LandingPageViews.as_view(), name='landing_page'),
    # path('pets/', pet_list, name='pet_list'),
    path('pets/', PetsListViews.as_view(), name='pet_list'),
    # path('detail/<int:id>/', pet_detail, name='pet_detail'),
    path('detail/<int:pk>/', PetDedailsView.as_view(), name='pet_detail'),
    path('detail/<slug:slug>/', PetDedailsView.as_view(), name='pet_detail_slug'),
    # path('detail/<int:pk>/<slug:slug>/', PetDedailsView.as_view(), name='pet_detail'),
    # path('like/<int:id>/', pet_like, name='pet_like'),
    path('like/<int:pk>/', PetLikeViews.as_view(), name='pet_like'),
    path('comment/<int:pk>/', PetCommentViews.as_view(), name='pet_comment'),
    # path('edit/<int:id>/', pet_edit, name='pet_edit'),
    path('edit/<int:pk>/', EditPetViews.as_view(), name='pet_edit'),
    # path('delete/<int:id>/', pet_delete, name='pet_delete'),
    path('delete/<int:pk>/', PetDeleteViews.as_view(), name='pet_delete'),
    # path('create/', pet_create, name='pet_create'),
    path('create/', CreatePetViews.as_view(), name='pet_create'),
]

template_project/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.views.static import serve
from django.utils.decorators import method_decorator

from allauth.account.views import LoginView

from axes.decorators import axes_dispatch
from axes.decorators import axes_form_invalid

from rest_framework import routers, serializers, viewsets

from contrib.home.views import home, url_with_arguments, reverse_views,\
                               template_tags, login_user, logout_user, register_user
from contrib.many_files.views import files
from contrib.osm.views import map
from contrib.django_exes.views import Login
from contrib.django_exes.forms import AxesLoginForm
from contrib.api_lead.views import UserViewSet, ItemListApiView, ItemDetailsApiView, api
from contrib.form_wizard.views import ContactWizard, formset_view, form_messages, widget_form
from contrib.notifications.views import get_notification
from contrib.sort_filter.views import filter, get_country, get_pub
from contrib.calculator.views import get_response
from contrib.currencies.views import exchange_rate, convert_currencies
from contrib.validators.views import validator
from contrib.django_polymorphic.views import AminalsViewSet
from contrib.test_urls.views import monthly_challenge, monthly_challenge_by_numbers
from rest_framework.authtoken.views import obtain_auth_token


LoginView.dispatch = method_decorator(axes_dispatch)(LoginView.dispatch)
LoginView.form_invalid = method_decorator(axes_form_invalid)(LoginView.form_invalid)

admin.autodiscover()

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
# router.register(r'items', ItemListApiView)

from django.contrib import admin
from django.utils.translation import gettext_lazy as _
 
admin.site.index_title = _('My Project')
admin.site.site_header = _('My Site Administration')
admin.site.site_title = _('Administration')


urlpatterns = i18n_patterns(
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^accounts/login/$', LoginView.as_view(form_class=AxesLoginForm), name='account_login'),
    url(r'^accounts/', include('allauth.urls')),

    path('rest-api/', include('rest_framework.urls')),
    path('api/', include(router.urls), name='apii'),
    path('api-items/', ItemListApiView.as_view(), name='items'),
    path('api-items/<int:pk>/', ItemDetailsApiView.as_view(), name='items detail'),
    path('api-js/', api, name='api-js'),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),

    path('<str:username>/<slug:article_value>/<str:id>', home, name='home_user_article'),
    path('reverse/', reverse_views, name='reverse_views'),
    path('', home, name='home'),
    path('url_with_arguments/', include('contrib.home.urls'), name='url_with_arguments'),
    path('files/', files, name='files'),
    path('map/', map, name='map'),
    path('wizard/', ContactWizard.as_view(), name='wizard'),
    path('formset/', formset_view, name='formset'),
    path('login/', Login.as_view(), name='login'),
    path('login/', Login.as_view(), name='login'),
    path('form_messages/', form_messages, name='form_message'),
    path('widget_form/', widget_form, name='widget_form'),
    path(r'captcha/', include('captcha.urls')),
    path('notifications/', get_notification, name='notifications'),
    path('filter/', filter, name='filter'),
    path('get_city/', get_country, name='get_country'),
    path('get_pub/', get_pub, name='get0pub'),
    path('response/', get_response, name='get_response'),
    path('exchange_rate/', exchange_rate, name='Exchange_rate'),
    path('ajax/convert_currencies', convert_currencies, name="convert_currencies"),
    path('validators/', validator, name='validators'),
    path('crud/', include('contrib.crud_operation.urls'), name='crud'),
    path('petstagram/', include('contrib.petstagram.urls'), name='petstagram'),
    path('based_views/', include('contrib.based_views.urls'), name='based_views'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('serializers/polymorphic/', AminalsViewSet.as_view({'get': 'list'}), name='animals_views_set'),
    path('templatetags/', template_tags, name='template_tags'),
    path('loginuser/', login_user, name='login_user'),
    path('logoutuser/', logout_user, name='logout_user'),
    path('registeruser/', register_user, name='register_user'),
    path('accounts/', include('contrib.accounts.urls')),
    path('chat/', include('contrib.chat.urls')),
    path('fibonacci-sequence/', include('contrib.fibonacci_sequence.urls'), name='fibonacci-sequence'),
    path('challenge/', include('contrib.test_urls.urls')),


    # url(r'^locked/$', locked_out, name='locked_out'),
)

urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls),  # NOQA
    url(r'^', include('cms.urls')),

)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns

contrib/petstagram/forms.py
from django import forms
from django.urls.conf import include

from .models import Comment, Pet


class CommenForm(forms.Form):
    text = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'form-control rounded-2',    
            }
        )
    )

class CommenViewsForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )


class PetForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for (_, field) in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
    
    class Meta:
        model = Pet
        exclude = ('user', 'slug')

contrib/petstagram/views.py
from contrib.petstagram.core.clead_up import clean_up_files
from django.contrib.auth import mixins as auth_mixins, views
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls.base import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView, DetailView
from django.views import generic as views
from .models import Pet, Like, Comment
from .forms import CommenForm, PetForm, CommenViewsForm
from contrib.accounts.decorators import user_required


def landing_page(request):
    return render(request, 'landing_page.html')

class LandingPageViews(TemplateView):
    template_name = 'landing_page.html'

def original(request):
    pass

def pet_list(request):
    pets = Pet.objects.all()
    context = {
        'pets': pets,
    }
    return render(request, 'partials/pet_list.html', context)


class PetsListViews(ListView):
    model = Pet
    template_name = 'partials/pet_list.html'
    context_object_name = 'pets'

class SearchResultsView(ListView):
    model = Pet
    template_name = 'search_results.html'

    def get_queryset(self): 
        query = self.request.GET.get('q')
        object_list = Pet.objects.filter(
            name=query
        )
        return object_list

@login_required
def pet_detail(request, id):
    pet = Pet.objects.get(pk=id)
    like = Pet.objects.filter(like__pet=id).count()
    if request.method == 'GET':
        context = {
            'pet': pet,
            'like': like,
            'form': CommenForm(),
            'can_delete': request.user == pet.user,
            'can_edit': request.user == pet.user,
            'can_like': request.user != pet.user,
            'has_liked': pet.like_set.filter(user_id=request.user.id).exists(),
            'can_comment': request.user != pet.user,

        }
        return render(request, 'partials/pet_detail.html', context)
    else:
        form = CommenForm(request.POST)
        if form.is_valid():
            comment = Comment(text=form.cleaned_data['text'])
            comment.pet = pet
            comment.user = request.user
            comment.save()
            return redirect('petstagram:pet_detail', id)
        context = {
            'pet': pet,
            'like': like,
            'form': form,
        }
        return render(request, 'partials/pet_detail.html', context)

class PetDedailsView(views.DetailView):
    model = Pet
    template_name = 'partials/pet_detail.html'
    context_object_name = 'pet'

    def get_context_data(self, pk=None, **kwargs):
        context = super().get_context_data(**kwargs)
        # import ipdb; ipdb.set_trace()
        pet = self.get_object()
        like = Pet.objects.filter(like__pet=pet.id).count()
        context['form'] = CommenForm()
        context['like'] = like
        context['can_delete'] = self.request.user == pet.user
        context['can_edit'] = self.request.user == pet.user
        context['can_like'] = self.request.user != pet.user
        context['has_liked'] = pet.like_set.filter(user_id=self.request.user.id).exists()
        context['can_comment'] = self.request.user != pet.user
        return context


@login_required
def pet_like(request, id):
    like = Like.objects.filter(user_id=request.user.id, pet_id=id).first()
    if like:
        like.delete()
    else:
        pet = Pet.objects.get(id=id)
        like = Like(pet=pet, user=request.user)
        like.save()
    return redirect('petstagram:pet_detail', id)


class PetLikeViews(views.View):
    def get(self, request, *args, **kwargs):
        # import ipdb; ipdb.set_trace()
        pet = Pet.objects.get(pk=self.kwargs['pk'])
        like = Like.objects.filter(user_id=request.user.id, pet_id=self.kwargs['pk']).first()
        if like:
            like.delete()
        else:
            like = Like(pet=pet, user=request.user)
            like.save()        
        return redirect('petstagram:pet_detail', pet.id)

class PetCommentViews(auth_mixins.LoginRequiredMixin, views.FormView):
    form_class = CommenViewsForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.user = self.request.user
        comment.pet = Pet.objects.get(pk=self.kwargs['pk'])
        comment.save()
        return redirect('petstagram:pet_detail', self.kwargs['pk'])

@login_required
def pet_delete(request, slug):
    pet = Pet.objects.get(slug=slug)

    if request.method == 'GET':
        context = {
            'pet': pet,
        }
        return render(request, 'partials/pet_delete.html', context)
    else:
        pet.delete()
        return redirect('petstagram:pet_list')

class PetDeleteViews(DeleteView):
    model = Pet
    template_name = 'partials/pet_delete.html'
    success_url = reverse_lazy('petstagram:pet_list')

    def dispatch(self, request, *args, **kwargs):
        pet = self.get_object()
        if pet.user_id != request.user.id:
            handler = self.http_method_not_allowed
            return handler(request, *args, **kwargs)
        return super().dispatch(request, *args, **kwargs)

@user_required(Pet)
def pet_edit(request, id):
    pet = Pet.objects.get(pk=id)
    if request.method == 'POST':
        old_image = pet.image_url
        form = PetForm(request.POST, request.FILES, instance=pet)
        if form.is_valid():
            if old_image:
                clean_up_files(old_image.path)
            form.save()
        return redirect('petstagram:pet_detail', pet.id)

    else:
        form = PetForm(instance=pet)
    context = {
        'form': form,
        'pet': pet,
    }
    return render(request, 'partials/pet_edit.html', context)

class EditPetViews(auth_mixins.LoginRequiredMixin, UpdateView):
    template_name = 'partials/pet_edit.html'
    model = Pet
    form_class = PetForm

    def get_absolute_url(self):
        success_url = reverse_lazy('petstagram:pet_detail', kwargs={'pk': self.object.id})
        return success_url

    def form_valid(self, form):
        old_image = self.get_object().image_url
        if old_image:
            clean_up_files(old_image.path)
        return super().form_valid(form)

@login_required
def pet_create(request):
    if request.method == 'POST':
        form = PetForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('petstagram:pet_list')
    else:
        form = PetForm()
    
    context = {
        'form': form,
    }

    return render(request, 'partials/pet_create.html', context)


class CreatePetViews(auth_mixins.LoginRequiredMixin, CreateView):
    template_name = 'partials/pet_create.html'
    model = Pet
    form_class = PetForm

    def get_absolute_url(self):
        success_url = reverse_lazy('petstagram:pet_detail', kwargs={'id': self.object.id})
        return success_url

    def get_login_url(self):
        return str('accounts:login')

    def form_valid(self, form):
        pet = form.save(commit=False)
        pet.user = self.request.user
        pet.save()
        return super().form_valid(form)

contrib/petstagram/templates/base_petstagram.html
{% load cms_tags menu_tags sekizai_tags static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <title>{% block title %}Petstagram{% endblock title %}</title>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link rel="icon" type="image/png" href="{% static 'instagram-png.png'%}">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
      {% block "extra-js" %}{% endblock %}
   </head>
   {% include 'partials/nav.html' %}
   {% block content %}{% endblock content %}
   {% block js %}{% endblock %}   
</body>
</html>

contrib/petstagram/templates/landing_page.html
{% extends 'base_petstagram.html'%}
{% load static %}
{% block content %}
<form action="{% url 'petstagram:search_results' %}" method="get">
   <input name="q" type="text" placeholder="Search by pet name
   ">
   <button class="button green srch-sbmt" type="submit">Търси</button>
 </form>
<div class="container">
   <div class="jumbotron parent">
      <img style="width: 100%" src="{% static 'animals.png'%}" alt="">
      <div class="absolute">
         <h1 class="display-4">Welcome to Petstagram</h1>
         <p class="lead">Share your pets photos.</p>
         <hr class="my-4">
         <div class="inner cover">
            <h1 class="cover-heading"></h1>
            <div class="row">
               <div class="col-lg-6">
                  <p class="lead">Already have an account? <br><a href="{% url 'accounts:login' %}" class="btn btn-lg btn-secondary">sign in</a></p>
               </div>
               <div class="col-lg-6">
                  <p class="lead"> Do not have an account? <br>
                     <a href="{% url 'accounts:sign_up' %}" class="btn btn-lg btn-secondary">sign up</a>
                  </p>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock %}

{% block js %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% endblock %}   

contrib/petstagram/templates/pet_pdf.html
{% extends 'base_petstagram.html' %}

{% block content %}
<h1>Pet</h1>
<table>
    <tr>
        {% if pet.type %}
        <td>
            Breed: 
        </td>
        <td>
            {{pet.type}}
        </td>
        {% endif %}
    </tr>
    <tr>
        <td>
            Name: 
        </td>
        <td>
            {{pet.name}}
        </td>
    </tr>
    <tr>
        <td>
            Age: 
        </td>
        <td>
            {{pet.age}}
        </td>
    </tr>
    <tr>
        <td>
            Description: 
        </td>
        <td>
            {{pet.description}}
        </td>
    </tr>
    <tr>
        <td>
            User: 
        </td>
        <td>
            {{pet.user}}
        </td>
    </tr>
</table>
{% endblock %}
 

contrib/petstagram/templates/search_results.html
<h1>Search Results</h1>

{% if object_list %}
{% for pet in object_list %}
<div class="col-xl-4">
    <div class="card" style="width: 18rem;">
        <img src="{{ pet.image_url.url }}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">{{ pet.type }} {{ pet.name }}, Age: {{ pet.age }}</h5>
            <p class="card-text">{{ pet.description }}</p>
            <a href="{% url 'petstagram:pet_detail' pet.pk pet.slug %}" class="btn btn-primary">See details</a>
        </div>
    </div>
</div>
{% endfor %}
{% else %}
<h2>No results found!!!</h2>
{% endif %}